train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-clean-100"
  use_bpe: True
  vocab_size: 250
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  use_bpe: True
  vocab_size: 250
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  use_bpe: True
  vocab_size: 250
  instance_transforms: ${transforms.instance_transforms.inference}
