train:
  _target_: src.datasets.LibrispeechDataset
  use_bpe: True
  data_dir: None
  part: "dev-clean"
  max_audio_length: 20.0
  max_text_length: 200
  limit: 2
  audio_augmentations: ${transforms.audio_transforms.train}
  instance_transforms: ${transforms.instance_transforms.train}
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.LibrispeechDataset
  use_bpe: True
  data_dir: None
  part: "dev-clean"
  max_audio_length: 20.0
  max_text_length: 200
  limit: 2
  instance_transforms: ${transforms.instance_transforms.inference}
