train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.BeamCERMetric
    name: "CER_(Beam)" # it is better to avoid spaces in names
  - _target_: src.metrics.BeamWERMetric
    name: "WER_(Beam)"
