defaults:
  - model: conformer
  - metrics: inference
  - datasets: example_eval # we do not want to run inference on training data
  - dataloader: example
  - transforms: example
  - _self_
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "../../input/conformer-1/model_best-24500.pth" # path to the pretrained model
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  use_bpe: False
  vocab_size: 100