train:
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
      - _target_: src.transforms.wav_augs.PitchShift
      - _target_: src.transforms.wav_augs.Noise
      - _target_: src.transforms.wav_augs.LowPassFilter
inference: