train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torchaudio.transforms.MelSpectrogram
      sample_rate: 16000
      - _target_: src.transforms.SpecAug
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
